In [1]:
import matplotlib.pyplot as plt
import numpy  as np

### Решение СЛАУ. Метод Зейделя. Метод Якоби

In [128]:
def Seidel(A, f, eps):
    x = np.zeros((len(A), 1))
    iter_num = 0
    while True:
        old_x = x.copy()

        for i in range(len(A)):
            sum = 0
            for j in range(len(A)):
                sum += A[i][j] * x[j] * (i != j)

            x[i] = (f[i] - sum) / A[i][i]

        iter_num += 1
        if max(np.absolute(x - old_x)) < eps:
            break
    return [x, iter_num]

In [129]:
def Jacobi(A, f, eps):
    x = np.zeros((len(A), 1))
    nx = np.ones((len(A), 1))
    iter_num = 0

    while True:
        x = nx.copy()
        for i in range(len(A)):
            sum = 0
            for j in range(len(A)):
                sum += A[i][j] * x[j] * (i != j)

            nx[i] = (f[i] - sum) / A[i][i]
        iter_num += 1
        if max(np.absolute(x - nx)) < eps:
            break

    return [x, iter_num]

In [152]:
n = 10
epsilon = 0.001
np.random.seed(1)
B = np.random.randint(-2, 2, (n, n))
for i in range(n):
    B[i][i] += np.random.randint(20, 30)
B

array([[24,  1, -2, -2,  1, -1,  1, -1,  1, -2],
       [-2, 28, -2,  1, -1, -2,  0, -1,  0, -2],
       [ 0, -1, 23, -2,  1, -2,  0, -2, -1,  0],
       [ 0, -2,  1, 27, -1, -1,  1,  0, -2,  0],
       [-1, -1, -1,  1, 29, -1,  0, -1, -1, -2],
       [-2, -1, -2, -2, -1, 21,  1,  0, -1, -2],
       [ 0,  1,  1,  0, -1, -1, 21,  1, -2, -2],
       [-1,  1, -2,  0, -2, -2, -1, 28, -1,  0],
       [ 1, -2, -2, -1,  1,  0,  1,  1, 27, -1],
       [-2,  0, -1,  1,  1,  0,  1, -1, -2, 30]])

In [153]:
np.random.seed(1)
x_1 = np.random.randint(-10, 10, (n, 1))
x_1

array([[ -5],
       [  1],
       [  2],
       [ -2],
       [ -1],
       [  1],
       [ -5],
       [  5],
       [-10],
       [  6]])

In [154]:
f = np.dot(B, x_1)
f

array([[-153],
       [  14],
       [  46],
       [ -39],
       [ -37],
       [  24],
       [ -89],
       [ 157],
       [-286],
       [ 195]])

In [155]:
print('Result (Jacoby method):')
print(Jacobi(B, f, epsilon)[0])
print('Accuracy: ')
print(abs(Jacobi(B, f, epsilon)[0] - x_1))

Result (Jacoby method):
[[-4.99988137]
 [ 1.00019241]
 [ 2.00024138]
 [-1.99989552]
 [-0.99986726]
 [ 1.00020144]
 [-4.99998038]
 [ 5.00016744]
 [-9.99994231]
 [ 6.00005228]]
Accuracy: 
[[1.18633496e-04]
 [1.92406114e-04]
 [2.41380974e-04]
 [1.04480825e-04]
 [1.32737940e-04]
 [2.01444264e-04]
 [1.96226719e-05]
 [1.67438151e-04]
 [5.76911290e-05]
 [5.22762235e-05]]


In [156]:
print('Result (Seidel method):')
print(Seidel(B, f, epsilon)[0])
print('Accuracy: ')
print(abs(Seidel(B, f, epsilon)[0] - x_1))

Result (Seidel method):
[[ -5.00000341]
 [  0.99999546]
 [  1.99999688]
 [ -2.00000175]
 [ -1.00000131]
 [  0.99999894]
 [ -5.00000013]
 [  4.99999939]
 [-10.00000043]
 [  5.99999973]]
Accuracy: 
[[3.41110763e-06]
 [4.54262488e-06]
 [3.11758492e-06]
 [1.75320481e-06]
 [1.30995075e-06]
 [1.05742060e-06]
 [1.32824177e-07]
 [6.12854665e-07]
 [4.26383663e-07]
 [2.73648081e-07]]
